#!/usr/bin/env bash

print_usage() {
	printf "\n$(basename "${0}") [-e] [-h] [-s]

    -e    Versão em inglês
    -h    Mostar estas informações e sair
    -s    Incluir informação sensível

Converte CV.md (Markdown) em PDF (Webkit).\n"
}

english=""
sensitive=""
while getopts ":ehs" opt
do
    case ${opt} in
        e)
            english=true
            ;;
        h)
            print_usage
            exit
            ;;
        s)
            sensitive=sensitive.md
            ;;
        \?)
            echo "Invalid option: -$OPTARG" 1>&2
            print_usage 1>&2
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

cv=CV.md
out=CV.pdf

if [[ -n "${english}" ]]
then
    cv=CV_en.md
    out=CV_en.pdf
    sensitive=sensitive_en.md
fi

if [[ -n "${sensitive}" ]]
then
    pandoc -V margin-left=8mm -V margin-right=8mm -V margin-top=8mm -V margin-bottom=8mm \
        -s -t html5 --css CV.css -o ${out} title.md ${sensitive} ${cv}
    exit
fi

pandoc -V margin-left=8mm -V margin-right=8mm -V margin-top=8mm -V margin-bottom=8mm \
    -s -t html5 --css CV.css -o ${out} title.md ${cv}
